[package]
name = "boba"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
members = [
  "crates/*",
]

[dependencies]
boba_core = { path = "./crates/boba_core" }
boba_3d = { path = "./crates/boba_3d" }
milk_tea_runner = { path = "./crates/milk_tea_runner" }
taro_renderer = { path = "./crates/taro_renderer" }

winit = "0.27"
env_logger = "0.9"
log = "0.4"
wgpu = "0.14"
pollster = "0.2"
cgmath = "0.18"
bytemuck = { version = "1.4", features = [ "derive" ] }
