[package]
name = "boba"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
members = [
  "crates/*",
]

[dependencies]
boba_app = { path = "./crates/boba_app" }
boba_window = { path = "./crates/boba_window" }
boba_renderer = { path = "./crates/boba_renderer" }