[package]
name = "boba"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
members = [
  "crates/*",
]

[dependencies]
boba_core = { path = "./crates/boba_core" }
black_tea = { path = "./crates/black_tea" }
