[package]
name = "taro_standard_shaders"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.16"

boba_3d = { path = "../boba_3d" }
taro_renderer = { path = "../taro_renderer" }
taro_standard_bindings = { path = "../taro_standard_bindings" }
