[package]
name = "boba_winit"
version = "0.1.0"
edition = "2021"

[dependencies]
boba_app = { path = "../boba_app" }
boba_renderer = { path = "../boba_renderer" }

log = "0.4"
env_logger = "0.9"
winit = "0.27"
wgpu = "0.14"
pollster = "0.2"
bytemuck = { version = "1.12", features = [ "derive" ] }