[package]
name = "taro_adapters"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
wgpu = "0.14"

boba_core = { path = "../boba_core" }
milk_tea = { path = "../milk_tea" }
taro_renderer = { path = "../taro_renderer" }
