[package]
name = "taro_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
boba_core = { path = "../boba_core" }
milk_tea_runner = { path = "../milk_tea_runner" }

log = "0.4"
winit = "0.27"
uuid = "1.2"
indexmap = "1.2"
pollster = "0.2"
anymap = "0.12"
naga = "0.10"
wgpu = { version="0.14", features = ["spirv", "naga"]}
bytemuck = { version = "1.4", features = [ "derive" ] }
image = { version = "0.24", default-features = false, features = ["png", "jpeg"]}
