[package]
name = "taro_renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
boba_core = { path = "../boba_core" }
boba_mesh = { path = "../boba_mesh" }
milk_tea_runner = { path = "../milk_tea_runner" }

winit = "0.27"
wgpu = "0.14"
pollster = "0.2"
bytemuck = { version = "1.4", features = [ "derive" ] }
image = { version = "0.24", default-features = false, features = ["png", "jpeg"]}