[package]
name = "taro_standard_bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.4", features = ["derive"] }

boba_3d = { path = "../boba_3d" }
taro_renderer = { path = "../taro_renderer" }
